FROM node:20-alpine
RUN apk add --no-cache libc6-compat python3 make g++
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps
COPY . .
CMD ["node_modules/.bin/cross-env", "PAYLOAD_CONFIG_PATH=src/payload.config.ts", "node_modules/.bin/payload", "migrate"]
